### ISSUE TITLE
rewrite colour support

### ISSUE THREAD

**Issue by nebulon42** [omniscale/magnacarto#13]
I found a HuSL implementation in your code, but it is currently not accessible from CartoCSS. Additionally, HSL colour definitions are not supported yet.
Maybe it would be beneficial to rewrite colour support to some generic colour type, which is converted to RGB(A) at the end. Compare https://github.com/mapbox/carto/pull/422, where I defined colours internally as HSLA including a flag if we are in perceptual space or not.

I tried to implement HSLA support, but got stuck at https://github.com/omniscale/magnacarto/blob/2537d1e3e227114cd09b6817c81b6a61accefadc/builder/mapnik/serialize.go#L580. My Go knowledge is not good enough to figure out how to input some more generic type to this function and do the necessary adjustments within. Maybe you have a hint.

Another thing: it might be better to move the HuSL implementation to some external library.

**Comment by nebulon42** [comment]
Currently working on a HUSL port to Go.

**Comment by olt** [comment]
Currently it's only used by [SetHue](https://github.com/omniscale/magnacarto/blob/2537d1e3e227114cd09b6817c81b6a61accefadc/color/functions.go#L88) which can be called from CartoCSS with [-mc-set-hue](https://github.com/omniscale/magnacarto/blob/2537d1e3e227114cd09b6817c81b6a61accefadc/mss/expression.go#L146).

**Comment by nebulon42** [comment]
My Go implementation of HUSL can be found here: https://github.com/husl-colors/husl-go

**Comment by nebulon42** [comment]
@olt What is the use case of this custom expression (-mc-set-hue)?

**Comment by olt** [comment]
It sets the hue of A to the hue of B. So that you get a new color with the same saturation/lightness of A, but the hue of B.

**Comment by nebulon42** [comment]
Solved by merging #15.
