### ISSUE TITLE
Unexpected value in filter when using regex match

### ISSUE THREAD

**Issue by horacer** [omniscale/magnacarto#20]
Hi guys,

I'm using the following css code to match specific countries for setting the appropriate label:

`["is_in:country_code"=~"DE|AT|CH|NL|BE"] { text-name: '[name]'; }`

This is supposed to work, however, magnacarto doesn't seem to like it.

`unexpected value in filter '~'`

I am not sure if this is really a magnacarto issue or if there is a better way to accomplish this?

**Comment by olt** [comment]
Regexp filters are not (yet) supported: https://github.com/omniscale/magnacarto#missing

**Comment by horacer** [comment]
As a workaround I'm now using:
`["is_in:country_code"="DE"], ["is_in:country_code"="AT"], ["is_in:country_code"="CH"], ["is_in:country_code"="NL"], ["is_in:country_code"="BE"] { text-name: '[name]'; }`

All right :) Thanks @olt

**Comment by nebulon42** [comment]
@horacer You might want to try if #30 solves your problem.

**Comment by olt** [comment]
#30 is merged
