### ISSUE TITLE
Only mml or yml too? What's your work flow?

### ISSUE THREAD

**Issue by emacgillavry** [omniscale/magnacarto#33]
We're investigating a process to easily design a map in Mapbox Studio Classic, but have it rendered by MapServer. MagnaCarto seemed to fit this workflow. However, your documentation explicitly mentions a project.mml file as input. However, the current Mapbox Studio Classic v0.3.3. only seems to generate a project.yml and project.xml file. Is MagnaCarto able to crunch either of these files into a MapServer map file? Or had we revert to an older version of Mapbox Studio Classic? Any thoughts on this?

**Comment by olt** [comment]
.mml files can be JSON or YAML, so it might work with your project.yml. 

Our workflow is to use magnaserv :-)

**Comment by emacgillavry** [comment]
Thanks for your clarification! Will check out magnaserv.
