### ISSUE TITLE
colour regressions

### ISSUE THREAD

**Issue by nebulon42** [omniscale/magnacarto#34]
Some regressions with my colour implementation were recently fixed in carto. These are very likely also present here.

What I have identified is that the mix function should definitely operate on RGB as operating on HSL/HUSL will yield different results. I'm not sure if the possibility to add/subtract colours is even present here.

Refs:
https://github.com/mapbox/carto/issues/441
https://github.com/mapbox/carto/issues/442
https://github.com/mapbox/carto/issues/443

**Comment by olt** [comment]
Ok, can you "revert" the change?

Add/subtract is not implemented right now and I don't think we actually need this. Compatibility with carto is a goal, but not 100% by all means.

**Comment by nebulon42** [comment]
Right, I will try to provide a fix for the mix function.
