### ISSUE TITLE
Conversion of opacity to MapServer is wrong

### ISSUE THREAD

**Issue by Nakaner** [omniscale/magnacarto#40]
Magnacarto does not properly convert the opacity value used with `comp-op: darken`.

If a CartoCSS style (e.g. admin.mss of OSM Carto) contains

```css
opacity: 0.4;
comp-op: darken;
```

Magnacarto will write a `OPACITY 0.4` into the LAYER section of the layer in the mapfile. Magnacarto should multiply the opacity values of CartoCSS by 100.

Note: `line-opacity` is not affected and converted properly.

**Comment by olt** [comment]
Thanks. It's now fixed. However, please note that `comp-op` is not (yet) supported by the Mapserver builder.
