### ISSUE TITLE
magnacarto-mapnik on windows?

### ISSUE THREAD

**Issue by Trevirirus** [omniscale/magnacarto#41]
How can i use my Mapnik 2.2 Installation with magnacarto or how am i able to compile magnacarto-mapnik to use it on **Windows**?

**Comment by olt** [comment]
You need to compile `magnacarto` and the `magnacarto-mapnik` plugin. Unfortunately I can't tell you how to do this on Windows... 

You can see how it is compiled on Linux/Mac in the Makefile https://github.com/omniscale/magnacarto/blob/master/Makefile

You also need to manually create the `vendor/github.com/omniscale/go-mapnik/mapnik_config.go` file.
This Bash script https://github.com/omniscale/go-mapnik/blob/master/configure.bash creates this `mapnik_config.go` file on Linux/Mac. Check if you have a `mapnik-config` command on your system and if you can call it with the same parameter as in the `configure.bash` script.

**Comment by Trevirirus** [comment]
Thanks for your fast answer. 
Would be great if the mapnik Plugin is integrated into your released binaries.

**Comment by olt** [comment]
It's not so easy to provide these binaries. 
The `magnacarto` binaries are cross-compiled (i.e. I build the Windows and Linux binaries from MacOS), but this is does not work for the `magnacarto-mapnik` plugin.
