### ISSUE TITLE
osm-carto: error building map: runtime error: index out of range

### ISSUE THREAD

**Issue by nebulon42** [omniscale/magnacarto#9]
I'm getting this error with the latest dev release (20151117 linux-amd64) when trying to compile osm-carto and one of my derived styles either with the mapnik2 or mapnik3 builder.

**Comment by olt** [comment]
Can you create a [gist](https://gist.github.com/) with the full error?

**Comment by nebulon42** [comment]
I'm happy to provide more info, but currently I'm not sure how. This line is the only output I get in addition to a timestamp. Is there some verbose or debug option?

**Comment by olt** [comment]
Can you provide the full command and styling you used?
Also please reduce the styling to the bare minimum (just remove blocks till the error disappears and then add that block/line back).

**Comment by nebulon42** [comment]
I tried with the latest master branches of the following projects:

osm-bright (https://github.com/mapbox/osm-bright) - worked

```
$./magnacarto -mml ~/dir/osm-bright/osm-bright/osm-bright.osm2pgsql.mml > test.xml
$
```

openstreetmap-carto (https://github.com/gravitystorm/openstreetmap-carto) - error

```
$./magnacarto -mml ~/dir/openstreetmap-carto/project.mml > test.xml
2015/11/24 19:27:16 error building map: runtime error: index out of range
$
```

HDM-CartoCSS (https://github.com/hotosm/HDM-CartoCSS) - regex error

```
$./magnacarto -mml ~/dir/HDM-CartoCSS/project.mml > test.xml
2015/11/24 19:30:58 error building map: unexpected value in filter '~' in /home/michael/projekte/osm/repos/carto/HDM-CartoCSS/base.mss line: 197 col: 11
$
```

ok, regex does not work yet. Missed that this style used regex. But osm-carto does not use regex and since you write osm-carto should work I thought I give it a try. This is all the info I'm able to give you now without dissecting osm-carto, which I don't want to do at the moment.

**Comment by olt** [comment]
Variables with booleans were not supported and a bug prevented a more meaningful error. Both is now fixed. The current openstreetmap-carto now also uses the mix function, which was not evaluated. This is now supported as well.

```
% time magnacarto -mml project.mml |wc -l
2015/11/26 17:36:10 File not found: data/antarctica-icesheet-outlines-3857/icesheet_outlines.shp
2015/11/26 17:36:10 File not found: data/antarctica-icesheet-polygons-3857/icesheet_polygons.shp
2015/11/26 17:36:10 File not found: symbols/shields/motorway_[width]x[height].svg
2015/11/26 17:36:10 File not found: symbols/shields/motorway_[width]x[height]_z16.svg
2015/11/26 17:36:10 File not found: symbols/shields/motorway_[width]x[height]_z18.svg
2015/11/26 17:36:10 File not found: symbols/shields/primary_[width]x[height].svg
2015/11/26 17:36:10 File not found: symbols/shields/primary_[width]x[height]_z16.svg
2015/11/26 17:36:10 File not found: symbols/shields/primary_[width]x[height]_z18.svg
2015/11/26 17:36:10 File not found: symbols/shields/secondary_[width]x[height].svg
2015/11/26 17:36:10 File not found: symbols/shields/secondary_[width]x[height]_z16.svg
2015/11/26 17:36:10 File not found: symbols/shields/secondary_[width]x[height]_z18.svg
2015/11/26 17:36:10 File not found: symbols/shields/tertiary_[width]x[height].svg
2015/11/26 17:36:10 File not found: symbols/shields/tertiary_[width]x[height]_z16.svg
2015/11/26 17:36:10 File not found: symbols/shields/tertiary_[width]x[height]_z18.svg
2015/11/26 17:36:10 File not found: symbols/shields/trunk_[width]x[height].svg
2015/11/26 17:36:10 File not found: symbols/shields/trunk_[width]x[height]_z16.svg
2015/11/26 17:36:10 File not found: symbols/shields/trunk_[width]x[height]_z18.svg
   38634

real    0m1.205s
user    0m1.783s
sys 0m0.081s
```

I haven't tested the result, but the number of lines looks good according to http://paulnorman.ca/blog/2015/11/openstreetmap-carto-complexity/

**Comment by nebulon42** [comment]
Was not aware of the mix function, either. :) But, great, thanks for the update.
